apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: three-tier-app
  namespace: staging

spec:
  replicas: 2

  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app: three-tier-app

  template:
    metadata:
      labels:
        app: three-tier-app

    spec:
      containers:
        - name: flask-app
          image: 622488711452.dkr.ecr.ap-south-1.amazonaws.com/three-tier-app:v3
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: DB_HOST
              value: three-tier-app-mysql.cnasygy06z8x.ap-south-1.rds.amazonaws.com

            - name: DB_USER
              value: db_username

            - name: DB_PASSWORD
              value: db_password

            - name: DB_NAME
              value: three_tier_app_db

            - name: S3_BUCKET_NAME
              value: eks-app-uploads-2026

            - name: AWS_DEFAULT_REGION
              value: ap-south-1

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY

  strategy:
    canary:
      stableService: three-tier-app-service

      steps:
        - setWeight: 25

        - pause:
            duration: 30s

        - setWeight: 50

        - pause:
            duration: 30s

        - setWeight: 75

        - pause:
            duration: 30s

        - setWeight: 100
