apiVersion: v1
kind: Service
metadata:
  name: three-tier-app-service
  namespace: staging
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-02176275e084fdc60,subnet-038b49b0579cd57a5,subnet-0859aa0875833b240,subnet-01377ac5ae71cc0c7"
spec:
  type: LoadBalancer
  selector:
    app: three-tier-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
